// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0cf9e677-da74-482f-8a2d-9325e616767d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5CAAcQ0gv",
    "aws_user_pools_web_client_id": "7oonctlq5rlc4ouv0ekd6f4bij"
};


export default awsmobile;
